added updated hipercontracer script

diff --git a/modified-hipercontracer/src/dbshell b/modified-hipercontracer/src/dbshell
--- a/modified-hipercontracer/src/dbshell
+++ b/modified-hipercontracer/src/dbshell
@@ -124,18 +124,20 @@ if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] ; then
    if [ "${dbbackend}" == "MariaDB" ] ; then
       command="$(which mariadb || true)"
       if [ "${command}" == "" ] ; then
-         command="mariadb"
+         echo >&2 "ERROR: MariaDB client (mariadb) not found. Is it installed?"
+         exit 1
       fi
    else
       command="$(which mysql || true)"
       if [ "${command}" == "" ] ; then
-         command="mysql"
+         echo >&2 "ERROR: MySQL client (mysql) not found. Is it installed?"
+         exit 1
       fi
    fi
    if [ "${dbport}" == "0" ] ; then
       dbport="3306"
    fi
-   parameters="${parameters} --host=\"${dbserver}\" --port=${dbport} --protocol=tcp --user=\"${dbuser}\" --password=\"${dbpassword}\" --database=\"${database}\""
+   parameters="${parameters} --silent --host=\"${dbserver}\" --port=${dbport} --protocol=tcp --user=\"${dbuser}\" --password=\"${dbpassword}\" --database=\"${database}\""
    if [ ${tls_enabled} -eq 1 ] && [ "${dbcafile}" != "" ] ; then
       if [ ${tls_check_certificate} -eq 1 ] || [ ${tls_check_hostname} -eq 1 ] ; then
          parameters="${parameters} --ssl-verify-server-cert"
@@ -150,12 +152,13 @@ elif [ "${dbbackend}" == "PostgreSQL" ] ; then
 
    command="$(which psql || true)"
    if [ "${command}" == "" ] ; then
-      command="psql"
+      echo >&2 "ERROR: PostgreSQL client (psql) not found. Is it installed?"
+      exit 1
    fi
    if [ "${dbport}" == "0" ] ; then
       dbport="5432"
    fi
-   parameters="--host=\"${dbserver}\" --port=${dbport} --username=\"${dbuser}\" --dbname=\"${database}\""
+   parameters="--quiet --host=\"${dbserver}\" --port=${dbport} --username=\"${dbuser}\" --dbname=\"${database}\""
    export PGPASSWORD="${dbpassword}"
    if [ ${tls_enabled} -eq 1 ] && [ "${dbcafile}" != "" ] ; then
       if [ ${tls_check_certificate} -eq 1 ] ; then
@@ -181,7 +184,8 @@ elif [ "${dbbackend}" == "MongoDB" ] ; then
    if [ "${command}" == "" ] ; then
       command="$(which mongo || true)"
       if [ "${command}" == "" ] ; then
-         command="mongosh"
+         echo >&2 "ERROR: MongoDB client (mongosh or mongo) not found. Is it installed?"
+         exit 1
       else
          oldCommand=1
       fi
@@ -210,6 +214,9 @@ elif [ "${dbbackend}" == "MongoDB" ] ; then
          fi
       fi
    fi
+   if [ ${oldCommand} -eq 0 ] ; then
+      parameters="${parameters} --quiet"
+   fi
 
 else
 
@@ -227,6 +234,8 @@ if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
    custom=""
    handler=""
    dbusername="${dbuser}"
+
+   # ====== MariaDB/MySQL ===================================================
    if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] ; then
       provider="mysql"
       handler="mysql_ssl"
@@ -240,15 +249,23 @@ if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
          driver="mysql8"
          jdbc="mysql"
 #       fi
-      if [ ${tls_check_certificate} -eq 1 ] || [ ${tls_check_hostname} -eq 1 ] ; then
-         ssl_verify_server="true"
+      if [ ${tls_enabled} -eq 1 ] && [ "${dbcafile}" != "" ] ; then
+         ssl_require="true"
+         if [ ${tls_check_certificate} -eq 1 ] || [ ${tls_check_hostname} -eq 1 ] ; then
+            ssl_verify_server="true"
+         else
+            ssl_verify_server="false"
+         fi
       else
+         ssl_require="false"
          ssl_verify_server="false"
       fi
       custom=",
-							\"ssl_require\": \"true\",
+							\"ssl_require\": \"${ssl_require}\",
 							\"ssl_verify.server\": \"${ssl_verify_server}\",
 							\"ssl.public.key.retrieve\": \"false\""
+
+   # ====== PostgreSQL ======================================================
    elif [ "${dbbackend}" == "PostgreSQL" ] ; then
       driver="postgres-jdbc"
       provider="postgresql"
@@ -269,6 +286,8 @@ if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
       if [ "${dbuser}" == "postgres" ] ; then
          dbusername="root"
       fi
+
+   # ====== Unsupported =====================================================
    else
       if [ ${QUIET} -eq 0 ] ; then
          echo >&2 "WARNING: DBeaver does not support ${dbbackend} backend!"
@@ -276,21 +295,27 @@ if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
       echo "" >"${DBEAVER_CONFIG_PREFIX}-data-source.json"
       echo "" >"${DBEAVER_CONFIG_PREFIX}-credentials-config.json"
    fi
+
    if [ "${driver}" != "" ] ; then
+      identifier="$(echo "${provider}://${dbusername}@${dbserver}:${dbport}/${database}" | md5sum --tag |  cut -d' ' -f4)"
+
       color="211,215,207"
       if [ "${dbusername}" == "importer" ] ; then
          color="237,212,0"
       elif [ "${dbusername}" == "researcher" ] ; then
-         color="org.jkiss.dbeaver.color.connectionType.qa.background"
+         color="0,127,253"
       elif [ "${dbusername}" == "maintainer" ] ; then
          color="114,159,207"
       elif [ "${dbusername}" == "root" ] ; then
          color="239,41,41"
       fi
+      # ansiColor="${color//,/;}"
+      # echo >&2 -e "\x1b[38;2;${ansiColor}mdbusername=${dbusername} database=${database} color=${color}\x1b[0m"
+
+      # ====== Generate DBeaver configuration ==================================
       if [ ${QUIET} -eq 0 ] ; then
          echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Writing DBeaver configuration to ${DBEAVER_CONFIG_PREFIX} ...\x1b[0m"
       fi
-      identifier="$(echo "${provider}://${dbusername}@${dbserver}:${dbport}/${database}" | md5sum --tag |  cut -d' ' -f4)"
       (
          cat << EOF
 {
@@ -336,8 +361,6 @@ if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
 							"ssl.client.cert": "${dbcertfile}",
 							"ssl.client.key": "${dbkeyfile}",
 							"ssl.method": "CERTIFICATES",
-							"ssl.require": "true",
-							"ssl.verify.server": "true",
 							"ssl.public.key.retrieve": "false",
 							"ssl.cipher.suites": ""${custom}
 						}
@@ -373,7 +396,7 @@ if [ ${QUIET} -eq 0 ] ; then
       echo -en "\x1b[37m"
    fi
 
-   if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] || [ "${dbbackend}" == "PostgreSQL" ] ; then
+   if [ "${dbbackend}" == "PostgreSQL" ] ; then
       export | grep "PGPASSWORD=\|PGSSL[A-Z]*=" | sort || true
    fi
    echo "${command} ${parameters}"
